services:
  app-dev:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env.development
    profiles:
      - dev

  db:
    image: postgres:15
    container_name: ecommerce_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env.development
    profiles:
      - dev

  app-prod:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env.production
    profiles:
      - prod

volumes:
  db_data:
