services:
  app_prod:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
    entrypoint: [ "/entrypoint.sh" ]
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - APP_ENV=production
    env_file:
      - .env.production
    profiles:
      - prod

  app_dev:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
    entrypoint: [ "/entrypoint.sh" ]
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    env_file:
      - .env.development
    profiles:
      - dev

  db:
    image: postgres:15
    container_name: ecommerce_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env.development
    profiles:
      - dev

volumes:
  db_data: